# fobj = open('./Text.txt', 'w', encoding='utf-8')
# fobj.write('在苍茫的大海上写首诗\n')
# fobj.write("狂风卷着乌云")
# fobj.close()

# fobj = open('./Text.txt', 'a')
# fobj.write("在大海和高山之间")
# fobj.write("海燕像黑色的闪电")
# fobj.close()

# fobj = open("./Test.txt", 'a')
# fobj.write("在苍茫的大海上\n")
# fobj.write("在苍茫的月亮上\n")
# fobj.write("在苍茫的高山上\n")
# fobj.write("在苍茫的光辉里\n")
# fobj.close()
# f = open("./Test.txt", 'r')
# print(f.read())
# print(f.read(12))
# print(f.readlines(1))
# print(f.readline())
# f.close()